name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]   # Se ejecuta cuando haces push a main
  workflow_dispatch:       # También lo puedes disparar manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Si tuvieras un framework como React/Vite, aquí va el build
      # - name: Build
      #   run: npm ci && npm run build

      - name: Subir artefacto (sitio estático)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
